spring: 
  profiles: 
   active: 
    - dev
---   
server: 
  port: 8001 
  
spring:
  profiles: dev  #开发环境
  application:
    name: microserivcecloud-dept                      #对外暴露的微服务的名称
  datasource:
     type: com.alibaba.druid.pool.DruidDataSource     #当前数据源的类型阿里云的
     driver-class-name: com.mysql.jdbc.Driver       #Mysql的驱动包org.git.mm.mysql.Driver
     url: jdbc:mysql://192.168.0.111:3306/cloud         #连接数据库的名称
     username: root
     password: root
     dbcp2:
      min-idle: 6              #当前数据库连接池的最小维持连接数
      initial-size: 6          #初始化连接
      max-total: 6            #最大连接数
      max-wait-millis: 200      #等待连接获取的做大超时时间
      
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml  #mybatis配置文件的路径
  type-aliases-package: com.spring.cloud.entity    #所有的entity的实体类路径
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                 #mapper映射的文件

eureka:
  client:                       #客户端注册进行eureka服务列表
   service-url:
     #defaultZone: http://localhost:7001/eureka   #入驻的地址必须与7001 defaultZone地址一致
     #配置将8001发布到3台Eureka集群配置中
    defaultZone: http://eureka7001.com:7001/eureka/
    #instance-id: microserivcecloud-dept8001   #自定义服务名称信息
    instance-id: microserivcecloud-dept8001-hystrix   #自定义服务名称信息,表示是一个熔断器的微服务
    prefer-ip-address: true     #访问路径显示IP地址  
    
info:
  app.name: microserivce-dept #工程的名称
  company.name: www.service.com   #公司的名称
  build.artifactId: $project.artifactId$
  build.version: $project.version$      
      
---

server: 
  port: 8002 
  
spring:
  profiles: test  #开发环境
  application:
    name: microserivcecloud-dept                      #对外暴露的微服务的名称
  datasource:
     type: com.alibaba.druid.pool.DruidDataSource     #当前数据源的类型阿里云的
     driver-class-name: com.mysql.jdbc.Driver       #Mysql的驱动包org.git.mm.mysql.Driver
     url: jdbc:mysql://192.168.0.111:3306/cloud1         #连接数据库的名称
     username: root
     password: root
     dbcp2:
      min-idle: 6              #当前数据库连接池的最小维持连接数
      initial-size: 6          #初始化连接
      max-total: 6            #最大连接数
      max-wait-millis: 200      #等待连接获取的做大超时时间
      
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml  #mybatis配置文件的路径
  type-aliases-package: com.spring.cloud.entity    #所有的entity的实体类路径
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                 #mapper映射的文件

eureka:
  client:                       #客户端注册进行eureka服务列表
   service-url:
     #defaultZone: http://localhost:7001/eureka   #入驻的地址必须与7001 defaultZone地址一致
     #配置将8001发布到3台Eureka集群配置中
    defaultZone: http://eureka7001.com:7001/eureka/
    #instance-id: microserivcecloud-dept8001   #自定义服务名称信息
    instance-id: microserivcecloud-dept8001-hystrix   #自定义服务名称信息,表示是一个熔断器的微服务
    prefer-ip-address: true     #访问路径显示IP地址  
    
info:
  app.name: microserivce-dept #工程的名称
  company.name: www.service.com   #公司的名称
  build.artifactId: $project.artifactId$
  build.version: $project.version$       
         